app/controllers/templates_controller.rb
app/views/templates/index.html.erb
config/routes.rb
db/seeds.rb
test/controllers/templates_controller_test.rb

implement the index to the template and db:seed

implement the index to the template and db:seed

---

app/assets/stylesheets/config/_fonts.scss
app/views/layouts/application.html.erb

font import from google and applied in css

---

app/controllers/templates_controller.rb
app/views/templates/_form.html.erb
app/views/templates/index.html.erb
app/views/templates/new.html.erb

Implement form, views

---

app/controllers/templates_controller.rb
app/views/shared/_navbar.html.erb
app/views/templates/edit.html.erb
app/views/templates/index.html.erb
app/views/templates/show.html.erb

Implement show/edit/create

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_login_form.scss
app/assets/stylesheets/components/_navbar.scss
app/views/devise/registrations/new.html.erb
app/views/shared/_navbar.html.erb

buttons and sign up

---

app/controllers/examples_controller.rb
app/controllers/templates_controller.rb
app/models/template.rb
app/views/examples/_form.html.erb
app/views/examples/new.html.erb
app/views/templates/show.html.erb
config/routes.rb
test/controllers/examples_controller_test.rb

examples_controller

---

app/assets/stylesheets/components/_button.scss
app/views/templates/_form.html.erb
app/views/templates/index.html.erb
app/views/templates/new.html.erb

Index template

---

Gemfile
Gemfile.lock
app/models/example.rb
config/initializers/openai.rb

create the api key in .env
openai.rb
method in example model to create example field

creating the connection to API and creating example field

---

app/controllers/examples_controller.rb
app/models/template.rb
app/views/templates/show.html.erb

Controller create a text

---

.gitignore
app/views/templates/_form.html.erb
app/views/templates/edit.html.erb
app/views/templates/index.html.erb
app/views/templates/show.html.erb

implement styles for template pages

---

app/controllers/examples_controller.rb
app/controllers/templates_controller.rb
app/views/examples/edit.html.erb
app/views/examples/new.html.erb
app/views/templates/_form.html.erb
app/views/templates/show.html.erb
config/routes.rb

Example edit controller

---

app/controllers/examples_controller.rb
app/controllers/input_fields_controller.rb
app/controllers/outputs_controller.rb
app/models/input_field.rb
app/models/output.rb
app/models/template.rb
app/views/outputs/edit.html.erb
app/views/templates/show.html.erb
config/routes.rb
db/migrate/20240307151156_remove_template_from_input_fields.rb
db/migrate/20240307151226_add_template_to_output.rb
db/schema.rb
test/controllers/input_fields_controller_test.rb
test/controllers/outputs_controller_test.rb

create the form for user input and output controller

---

app/controllers/examples_controller.rb
app/controllers/pages_controller.rb
app/controllers/templates_controller.rb
app/views/pages/home.html.erb
config/routes.rb

start button

---

app/controllers/examples_controller.rb
app/controllers/input_fields_controller.rb
app/controllers/outputs_controller.rb
app/models/example.rb
app/models/output.rb
app/models/template.rb
app/views/outputs/edit.html.erb
app/views/outputs/show.html.erb

Input fields output edit

---

app/controllers/input_fields_controller.rb
app/controllers/outputs_controller.rb
app/models/input_field.rb
app/models/output.rb
app/views/outputs/_form.html.erb
app/views/outputs/edit.html.erb
app/views/outputs/new.html.erb

validation

---

app/controllers/application_controller.rb
app/views/devise/sessions/new.html.erb
app/views/outputs/_form.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/templates/index.html.erb
db/seeds.rb

Home page flow, template button, my template nvbar

Home page flow, template button, my template nvbar

---

app/controllers/templates_controller.rb
app/models/example.rb
app/models/template.rb
app/views/examples/edit.html.erb
app/views/outputs/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/templates/_form.html.erb
app/views/templates/index.html.erb
app/views/templates/show.html.erb
db/seeds.rb

new edit example

---

app/views/outputs/show.html.erb
app/views/pages/home.html.erb

Edit back button

---

app/controllers/outputs_controller.rb
app/models/example.rb
app/models/output.rb
app/views/outputs/_form.html.erb

Output field

---

app/models/example.rb
app/views/pages/home.html.erb

lenght example field

---

app/assets/stylesheets/components/_tag.scss
app/views/examples/edit.html.erb

margin pills

---

app/controllers/templates_controller.rb
app/models/example.rb
app/models/example_field.rb
app/views/templates/index.html.erb
app/views/templates/show.html.erb
config/routes.rb

button delete

---

app/views/outputs/show.html.erb

email button

---

app/assets/stylesheets/config/_presentation.scss
app/views/outputs/_form.html.erb
app/views/outputs/new.html.erb
app/views/pages/home.html.erb

back button and small UI alignements

small UI changes
